export const purchaseOrderMock = [
  {
    id: 101,
    referenceNo: "PO-0001",
    vendor: {
      id: 33,
      name: "Acme Supplies Sdn Bhd",
      email: "finance@acme.test",
      phone: "+603-1234-5678",
    },
    issueDate: "2024-03-01",
    expectedDeliveryDate: "2024-03-15",
    currency: {
      code: "MYR",
      symbol: "RM",
      exchangeRate: 1,
    },
    status: "approved",
    totals: {
      subtotal: 2141.5,
      tax: 128.49,
      shipping: 25.0,
      discount: 0,
      grandTotal: 2294.99,
      amountBilled: 0,
      amountReceived: 0,
    },
    items: [
      {
        lineId: "101-1",
        name: "Thermal Paper Roll",
        description: "80mm x 80mm",
        quantity: 50,
        unitName: "roll",
        unitCost: 12.5,
        taxRate: 0.06,
        taxAmount: 37.5,
        lineTotal: 625,
      },
      {
        lineId: "101-2",
        name: "Barcode Scanner",
        description: "USB wired",
        quantity: 5,
        unitName: "unit",
        unitCost: 305.3,
        taxRate: 0.06,
        taxAmount: 91.59,
        lineTotal: 1526.5,
      },
    ],
    approvals: {
      approvedBy: {
        staffId: 7,
        name: "Nurul Aisyah",
      },
      approvedAt: "2024-03-02T04:32:11Z",
    },
    notes: "Consolidated restock for March retail operations.",
  },
  {
    id: 102,
    referenceNo: "PO-0002",
    vendor: {
      id: 12,
      name: "Global Office Traders",
      email: "sales@globaloffice.test",
      phone: "+603-7654-3210",
    },
    issueDate: "2024-03-10",
    expectedDeliveryDate: "2024-03-17",
    currency: {
      code: "MYR",
      symbol: "RM",
      exchangeRate: 1,
    },
    status: "draft",
    totals: {
      subtotal: 870.0,
      tax: 52.2,
      shipping: 0,
      discount: 20.0,
      grandTotal: 902.2,
      amountBilled: 0,
      amountReceived: 0,
    },
    items: [
      {
        lineId: "102-1",
        name: "Executive Chair",
        description: "Mesh back",
        quantity: 4,
        unitName: "unit",
        unitCost: 217.5,
        taxRate: 0.06,
        taxAmount: 52.2,
        lineTotal: 870,
      },
    ],
    approvals: null,
    notes: "Pending budget confirmation from finance.",
  },
];

export const billMock = [
  {
    id: 501,
    billNo: "BILL-2024-031",
    referenceNo: "PO-0001",
    vendor: {
      id: 33,
      name: "Acme Supplies Sdn Bhd",
    },
    issueDate: "2024-03-18",
    dueDate: "2024-04-17",
    currency: {
      code: "MYR",
      symbol: "RM",
      exchangeRate: 1,
    },
    status: "open",
    totals: {
      subtotal: 2141.5,
      tax: 128.49,
      discount: 0,
      adjustments: 0,
      grandTotal: 2269.99,
      amountPaid: 0,
      amountDue: 2269.99,
    },
    items: [
      {
        lineId: "501-1",
        name: "Thermal Paper Roll",
        quantity: 50,
        unitCost: 12.5,
        taxRate: 0.06,
        lineTotal: 625,
      },
      {
        lineId: "501-2",
        name: "Barcode Scanner",
        quantity: 5,
        unitCost: 305.3,
        taxRate: 0.06,
        lineTotal: 1526.5,
      },
    ],
    ledgerPostings: [
      {
        accountId: 1100,
        accountName: "Accounts Payable",
        type: "credit",
        amount: 2269.99,
      },
      {
        accountId: 5100,
        accountName: "Office Supplies Expense",
        type: "debit",
        amount: 2141.5,
      },
      {
        accountId: 2150,
        accountName: "Sales Tax Payable",
        type: "debit",
        amount: 128.49,
      },
    ],
  },
  {
    id: 502,
    billNo: "BILL-2024-032",
    referenceNo: "PO-0002",
    vendor: {
      id: 12,
      name: "Global Office Traders",
    },
    issueDate: "2024-03-19",
    dueDate: "2024-04-18",
    currency: {
      code: "MYR",
      symbol: "RM",
      exchangeRate: 1,
    },
    status: "draft",
    totals: {
      subtotal: 870.0,
      tax: 52.2,
      discount: 20.0,
      adjustments: 0,
      grandTotal: 902.2,
      amountPaid: 0,
      amountDue: 902.2,
    },
    items: [
      {
        lineId: "502-1",
        name: "Executive Chair",
        quantity: 4,
        unitCost: 217.5,
        taxRate: 0.06,
        lineTotal: 870,
      },
    ],
    ledgerPostings: [],
  },
];

export const accountsMock = [
  {
    id: 1000,
    number: "1010",
    name: "Cash on Hand",
    accountType: "Asset",
    detailType: "Petty Cash",
    currency: {
      code: "MYR",
      symbol: "RM",
    },
    debitTotal: 12450.75,
    creditTotal: 14592.25,
    primaryBalance: -2141.5,
    children: [],
  },
  {
    id: 2000,
    number: "2100",
    name: "Accounts Payable",
    accountType: "Liability",
    detailType: "Trade Creditors",
    currency: {
      code: "MYR",
      symbol: "RM",
    },
    debitTotal: 5250.0,
    creditTotal: 8200.0,
    primaryBalance: 2950.0,
    children: [
      {
        id: 2101,
        number: "2110",
        name: "Accounts Payable - Local",
        accountType: "Liability",
        detailType: "Accounts Payable",
        currency: {
          code: "MYR",
          symbol: "RM",
        },
        debitTotal: 1250.0,
        creditTotal: 2200.0,
        primaryBalance: 950.0,
      },
    ],
  },
];

export default {
  purchaseOrders: purchaseOrderMock,
  bills: billMock,
  accounts: accountsMock,
};
